# Generated by Django 5.0 on 2024-02-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=180)),
                ('firstname', models.CharField(max_length=180)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
